# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8bbb3b2c762b2b5126a1d1fab7e82734"
name = "remix-tutorial"
handle = "remix-tutorial-15"
application_url = "https://pursuit-ruth-badge-proudly.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "shoesshopdemo.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://pursuit-ruth-badge-proudly.trycloudflare.com/auth/callback",
  "https://pursuit-ruth-badge-proudly.trycloudflare.com/auth/shopify/callback",
  "https://pursuit-ruth-badge-proudly.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
